chore: testing husky
chore: testing husky

chore: testing husky

chore: testing husky

chore: testing husky

chore: testing husky

chore: testing husky

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,34 +1,36 @@
-#!/bin/sh
-​
-FORBIDDEN_HTTPS_URL="https://github.com/msdio/stackticon.git" # insert your remote url (https)
-FORBIDDEN_SSH_URL="git@github.com:msdio/stackticon.git" # insert your remote url (ssh)
-FORBIDDEN_REF="refs/heads/main" # insert branch ref
-​
-ARR_GIT_PARAMS=($(echo $HUSKY_GIT_PARAMS))
-ARR_GIT_STDIN=($(echo $HUSKY_GIT_STDIN))
-​
-remote=${ARR_GIT_PARAMS[0]}
-url=${ARR_GIT_PARAMS[1]}
-​
-local_ref=${ARR_GIT_STDIN[0]}
-local_sha=${ARR_GIT_STDIN[1]}
-remote_ref=${ARR_GIT_STDIN[2]}
-remote_sha=${ARR_GIT_STDIN[3]}
-​
-if [ "$url" != "$FORBIDDEN_HTTPS_URL" -a "$url" != "$FORBIDDEN_SSH_URL" ]
-then
-    exit 0 # disable in Forked Project
+#!/usr/bin/env sh
+
+protected_branch='main'
+policy='[Policy] DO NOT PUSH it directly to '$protected_branch' branch'
+
+current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
+
+push_command=$(ps -ocommand= -p $PPID)
+
+is_destructive='force|delete|\-f'
+
+will_remove_protected_branch=':'$protected_branch
+
+do_exit(){
+  echo $policy
+  exit 1
+}
+
+if [[ $push_command =~ $is_destructive ]] && [ $current_branch = $protected_branch ]; then
+  do_exit
 fi
-​
-if [ "$remote_ref" == "$FORBIDDEN_REF" ]
-then
-    echo "DO NOT PUSH it directly to main branch"
-    exit 1
+
+if [[ $push_command =~ $is_destructive ]] && [[ $push_command =~ $protected_branch ]]; then
+  do_exit
 fi
-​
-exit 0
+
+if [[ $push_command =~ $will_remove_protected_branch ]]; then
+  do_exit
+fi
+
+unset do_exit
 
 
 # check if there is an error when build project
-echo "Checking errors when build project"
+echo "[husky] Checking errors when build project"
 yarn build
